version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=dev-secret-change-in-production
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
      - OPENROUTER_API_URL=https://openrouter.ai/api/v1
    volumes:
      - ./prisma:/app/prisma
      - db-data:/app/prisma/db
    networks:
      - app-network
    restart: unless-stopped

  # Optional: PostgreSQL for production
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=aicodingagent
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=aicodingagent
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  # Optional: Redis for session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  postgres-data:
  redis-data: